### ISSUE TITLE
Tutorial "Getting Started: 4. Edit Simulation Conditions" does not work until initialize_mode = MANUAL

### ISSUE THREAD

**Issue by Sulles** [ut-issl/s2e-documents#102]
### Description
The tutorial, "Getting Started: 4. Edit Simulation Conditions" (https://www.space.t.u-tokyo.ac.jp/s2e-documents/Tutorials/GettingStarted.html) asks the user to modify the `sample_satellite.ini` file to initialize the satellite to a non-zero rotation rate and then to verify that the output log shows the same non-zero rotation rate. However, this tutorial does not mention that this only works if the `initialize_mode` variable is changed from `CONTROLLED` to `MANUAL`.

### Conditions of occurrence
Built on Windows10, x86 using VS installation instructions

### Additional information

This [logs.zip](https://github.com/ut-issl/s2e-documents/files/13894160/logs.zip) file contains two identical logs where both have defined the initial angular velocity as:
```
// Initial angular velocity at body frame [rad/s]
initial_angular_velocity_b_rad_s(0) = 0.1234
initial_angular_velocity_b_rad_s(1) = 0.0
initial_angular_velocity_b_rad_s(2) = 0.0
``` 
But the first has defined `initialize_mode = MANUAL`, and the second has defined `initialize_mode = CONTROLLED`. Observe the difference between the two angular velocity observer graphs below:

![Figure_1](https://github.com/ut-issl/s2e-core/assets/25142540/dff66c33-7949-4e70-bdda-f34fd1c84d44)
![Figure_2](https://github.com/ut-issl/s2e-core/assets/25142540/c39fd402-2de7-4b5b-99e2-d4689e71a2e5)

## Tasks
- [ ] Add instruction to change `initialize_mode` from `CONTROLLED` to `MANUAL` for tutorial "Getting Started: 4. Edit Simulation Conditions"

## Impact
A tutorial does not work as intended

## Priority
very low

**Comment by 200km** [comment]
@Sulles Thank you very much for your comment. The problem happens because the default value of [ATTITUDE:initialize_mode](https://github.com/ut-issl/s2e-core/blob/bf1e8aecccccaf0171d399eaa2dbe247f23366e8/data/sample/initialize_files/sample_satellite.ini#L10) was unexpectedly changed. So, I made a [PR](https://github.com/ut-issl/s2e-core/pull/567) to change the default value.
Your [PR](https://github.com/ut-issl/s2e-documents/pull/103) also looks useful in clarifying the description of the tutorial. I added a small comment to the PR.
